language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - python train_model.py
  - pytest test_model.py
<<<<<<< HEAD
=======
# Final trigger
>>>>>>> 28e6cab0ae5fd141bca43f8bec55c417b841d42b
