language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - python train_model.py
  - pytest test_model.py
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
# Final trigger
>>>>>>> 28e6cab0ae5fd141bca43f8bec55c417b841d42b
>>>>>>> 453c3e461fe111aa33fdd0fa711ec2b4021a328d
>>>>>>> 3f0a3eb083d800cd9a1d9773df8a73522a8bc59c
